// Auto-generated by Supabase CLI — do not edit manually
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          phone: string | null
          role: 'user' | 'agency' | 'promoter' | 'admin' | 'superadmin'
          is_verified: boolean
          subscription: 'free' | 'basic' | 'pro' | 'enterprise'
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      listings: {
        Row: {
          id: string
          slug: string
          title: string
          title_ar: string | null
          description: string | null
          description_ar: string | null
          type: string
          transaction: string
          price: number
          price_negotiable: boolean
          area: number | null
          bedrooms: number | null
          bathrooms: number | null
          floor: number | null
          total_floors: number | null
          year_built: number | null
          city: string
          district: string | null
          address: string | null
          features: Json
          status: string
          rejection_reason: string | null
          is_premium: boolean
          is_featured: boolean
          is_verified: boolean
          quality_score: number
          views_count: number
          contacts_count: number
          favorites_count: number
          owner_id: string
          agency_id: string | null
          created_at: string
          updated_at: string
          published_at: string | null
          expires_at: string | null
          meta_title: string | null
          meta_description: string | null
          search_vector: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['listings']['Row'],
          'id' | 'created_at' | 'updated_at' | 'search_vector'
        >
        Update: Partial<Database['public']['Tables']['listings']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
