import type { Prestataire, PresataireCardData } from '@/types/prestataire'

export const PRESTATAIRES: Prestataire[] = [
  {
    slug: 'maitre-karima-el-fassi',
    name: 'Maître Karima El Fassi',
    title: 'Notaire associée',
    category: 'notaire',
    city: 'Casablanca',
    district: 'Maarif',
    bio: "Notaire associée au sein de l'étude El Fassi depuis 18 ans, Maître Karima El Fassi s'est imposée comme l'une des références du droit immobilier à Casablanca. Elle intervient sur l'ensemble des actes notariaux : ventes, successions, donations, hypothèques et règlements de copropriété. Connue pour sa pédagogie et sa rigueur, elle accompagne aussi bien des particuliers primo-accédants que des promoteurs immobiliers d'envergure, de la rédaction du compromis à la signature de l'acte définitif. Son étude est équipée d'outils digitaux permettant un suivi transparent et sécurisé des dossiers. Elle intervient en français, arabe et anglais.",
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1400&h=500&fit=crop',
    rating: 4.9,
    reviewCount: 47,
    responseTime: 'Répond sous 2h',
    isVerified: true,
    isPremium: true,
    services: ['Vente immobilière', 'Succession', 'Prêt hypothécaire', 'Copropriété', 'Donation'],
    priceInfo: 'À partir de 2 500 MAD',
    completedProjects: 312,
    yearsExperience: 18,
    languages: ['Français', 'Arabe', 'Anglais'],
    specializations: ['Droit immobilier', 'Droit de la famille', 'Droit des successions'],
    certifications: ['Ordre des Notaires du Maroc', 'Formation continue CNRN 2024', 'Spécialisation droit foncier'],
    availability: 'disponible',
    phone: '+212 5 22 XX XX XX',
    email: 'k.elfassi@etude-elfassi.ma',
    website: 'www.etude-elfassi.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&h=500&fit=crop',
        caption: 'Transaction résidentielle — Maarif, Casablanca',
      },
      {
        url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=700&h=500&fit=crop',
        caption: 'Actes de succession — dossier familial',
      },
      {
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&h=500&fit=crop',
        caption: 'Étude notariale — Casablanca Centre',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Hamid Benkirane',
        authorInitials: 'HB',
        rating: 5,
        date: '15 mars 2024',
        text: "Maître El Fassi a géré notre succession familiale avec une efficacité et une bienveillance exceptionnelles. Dossier complexe avec plusieurs héritiers traité en 3 semaines. Disponible, claire et rassurante. Je recommande sans hésiter.",
        projectType: 'Succession',
      },
      {
        id: 'r2',
        author: 'Leila Moussaoui',
        authorInitials: 'LM',
        rating: 5,
        date: '2 février 2024',
        text: "Premier achat immobilier stressant, mais Maître El Fassi a rendu le processus transparent et serein. Elle a expliqué chaque étape, anticipé les problèmes et remis les clés dans les délais prévus. Parfait.",
        projectType: 'Vente immobilière',
      },
      {
        id: 'r3',
        author: 'Rachid Alaoui',
        authorInitials: 'RA',
        rating: 5,
        date: '18 novembre 2023',
        text: "Professionnalisme irréprochable. Notre dossier de copropriété était compliqué, elle a tout réglé avec calme et rigueur. Équipe réactive et bureau très bien équipé.",
        projectType: 'Copropriété',
      },
      {
        id: 'r4',
        author: 'Sofia Tazi',
        authorInitials: 'ST',
        rating: 4,
        date: '5 octobre 2023',
        text: "Très bonne prestataire, connaissance pointue du droit immobilier marocain. Un léger délai sur la préparation des actes finaux mais la qualité était au rendez-vous.",
        projectType: 'Vente immobilière',
      },
    ],
  },

  {
    slug: 'maitre-hassan-bensouda',
    name: 'Maître Hassan Bensouda',
    title: 'Notaire — Étude Bensouda',
    category: 'notaire',
    city: 'Rabat',
    district: 'Agdal',
    bio: "Fort de 24 ans de pratique notariale à Rabat, Maître Hassan Bensouda est une référence en matière de transactions immobilières dans la région capitale. Ancien président de la chambre des notaires de Rabat-Salé, il conseille régulièrement des investisseurs étrangers et marocains résidant à l'étranger souhaitant acquérir des biens au Maroc. Son étude traite plusieurs centaines de dossiers par an avec un taux de satisfaction client supérieur à 98 %. Expert reconnu en droit foncier, il intervient également en expertise judiciaire auprès des tribunaux de commerce.",
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1400&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 89,
    responseTime: 'Répond sous 24h',
    isVerified: true,
    isPremium: false,
    services: ['Transaction immobilière', 'Droit de la famille', 'Succession', 'Investissement étranger', 'Expertise judiciaire'],
    priceInfo: 'À partir de 3 000 MAD',
    completedProjects: 520,
    yearsExperience: 24,
    languages: ['Français', 'Arabe', 'Espagnol'],
    specializations: ['Droit foncier', 'Investissement étranger', 'Expertise judiciaire'],
    certifications: ['Ordre des Notaires du Maroc', 'Ex-Président chambre Rabat-Salé', 'Expert judiciaire agréé'],
    availability: 'sur_rdv',
    phone: '+212 5 37 XX XX XX',
    email: 'contact@bensouda-notaire.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=700&h=500&fit=crop',
        caption: 'Étude notariale — Agdal, Rabat',
      },
      {
        url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=700&h=500&fit=crop',
        caption: 'Conseil en investissement immobilier',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Karim Lahrichi',
        authorInitials: 'KL',
        rating: 5,
        date: '10 avril 2024',
        text: "Maître Bensouda a facilité mon acquisition depuis la France avec une fluidité remarquable. Procurations, actes, titre foncier : tout a été géré à distance sans aucun accroc. Un grand professionnel.",
        projectType: 'Investissement étranger',
      },
      {
        id: 'r2',
        author: 'Amina Filali',
        authorInitials: 'AF',
        rating: 5,
        date: '22 janvier 2024',
        text: "Très sérieux, très compétent. Notre succession impliquait des biens dans plusieurs villes, il a tout coordonné impeccablement. Son expérience se ressent dès le premier rendez-vous.",
        projectType: 'Succession',
      },
      {
        id: 'r3',
        author: 'Omar Chraibi',
        authorInitials: 'OC',
        rating: 4,
        date: '8 décembre 2023',
        text: "Bon notaire, expérimenté et rigoureux. Les délais sont parfois longs vu le volume de dossiers, mais le résultat est toujours impeccable.",
        projectType: 'Transaction immobilière',
      },
    ],
  },

  {
    slug: 'youssef-alami-agent',
    name: 'Youssef Alami',
    title: 'Agent immobilier certifié',
    category: 'agent',
    city: 'Casablanca',
    district: 'Racine',
    bio: "Youssef Alami est l'un des agents immobiliers les plus actifs sur le marché casablancais. En 12 ans de carrière, il a accompagné plus de 870 transactions dans les quartiers premium de Casablanca : Racine, Maarif, Anfa et Casa Finance City. Son approche se distingue par une évaluation précise des biens basée sur des données marché réelles, un réseau d'acquéreurs qualifiés et un suivi personnalisé de la première visite jusqu'à la remise des clés. Certifié FNAIM Maroc, il intervient également en conseil patrimonial pour les investisseurs locatifs.",
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 134,
    responseTime: 'Répond sous 1h',
    isVerified: true,
    isPremium: true,
    services: ['Vente', 'Location', 'Estimation gratuite', 'Investissement locatif', 'Conseil patrimonial'],
    priceInfo: '2,5 % de la transaction',
    completedProjects: 870,
    yearsExperience: 12,
    languages: ['Français', 'Arabe', 'Anglais'],
    specializations: ['Résidentiel premium', 'Investissement locatif', 'Vente en VEFA'],
    certifications: ['FNAIM Maroc', 'Carte professionnelle N° 2847', 'Formation continue SNPI 2024'],
    availability: 'disponible',
    phone: '+212 6 61 XX XX XX',
    email: 'y.alami@alami-immo.ma',
    website: 'www.alami-immo.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=700&h=500&fit=crop',
        caption: 'Appartement terrasse vendu — Racine, 3,2 M MAD',
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Penthouse livré — Maarif, 5,8 M MAD',
      },
      {
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=700&h=500&fit=crop',
        caption: 'Studio meublé loué — CFC, 14 000 MAD/mois',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Mehdi Ziani',
        authorInitials: 'MZ',
        rating: 5,
        date: '20 avril 2024',
        text: "Youssef a vendu notre appartement en 11 jours au-dessus du prix demandé. Son réseau d'acheteurs est impressionnant et sa connaissance du quartier Racine est encyclopédique. Très satisfait.",
        projectType: 'Vente',
      },
      {
        id: 'r2',
        author: 'Nadia Benhaddou',
        authorInitials: 'NB',
        rating: 5,
        date: '3 mars 2024',
        text: "Agent hors pair. Il a trouvé notre appartement idéal en 2 visites après avoir parfaitement cerné nos critères. Négociation menée avec brio. Je le recommande à tous mes proches.",
        projectType: 'Achat',
      },
      {
        id: 'r3',
        author: 'Hassan El Idrissi',
        authorInitials: 'HE',
        rating: 5,
        date: '15 janvier 2024',
        text: "Très pro, très réactif. Mon bien loué en 5 jours avec un locataire solvable. Il gère tout de A à Z, de l'annonce au bail.",
        projectType: 'Location',
      },
      {
        id: 'r4',
        author: 'Sanae Berrada',
        authorInitials: 'SB',
        rating: 4,
        date: '2 novembre 2023',
        text: "Bon agent, honnête et compétent. Quelques visites inutiles au départ mais l'achat s'est très bien conclu.",
        projectType: 'Achat',
      },
    ],
  },

  {
    slug: 'nadia-chraibi-marrakech',
    name: 'Nadia Chraibi',
    title: 'Conseillère en immobilier haut de gamme',
    category: 'agent',
    city: 'Marrakech',
    district: 'Guéliz',
    bio: "Spécialiste du marché haut de gamme marrakchi depuis 8 ans, Nadia Chraibi a développé une expertise unique sur les riads de la Médina, les villas de la Palmeraie et les appartements de Guéliz et Hivernage. Ancienne responsable marketing dans le secteur hôtelier de luxe, elle apporte à chaque transaction une connaissance approfondie du potentiel locatif saisonnier et de la rentabilité nette. Elle accompagne une clientèle internationale (France, Belgique, UK, Gulf) et travaille en français, anglais et arabe.",
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1400&h=500&fit=crop',
    rating: 5.0,
    reviewCount: 28,
    responseTime: 'Répond sous 3h',
    isVerified: true,
    isPremium: true,
    services: ['Riads & Villas', 'Location saisonnière', 'Investissement étranger', 'Estimation & Valorisation', 'Gestion locative'],
    priceInfo: 'Sur devis',
    completedProjects: 156,
    yearsExperience: 8,
    languages: ['Français', 'Arabe', 'Anglais'],
    specializations: ['Riads Médina', 'Villas Palmeraie', 'Clientèle internationale'],
    certifications: ['Carte professionnelle agence', 'Membre FNAIM Marrakech', 'Formation luxury real estate Paris 2022'],
    availability: 'disponible',
    phone: '+212 6 62 XX XX XX',
    email: 'nadia@chraibi-luxury.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=700&h=500&fit=crop',
        caption: 'Riad 6 suites vendu — Médina, 4,2 M MAD',
      },
      {
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&h=500&fit=crop',
        caption: 'Villa contemporaine — Palmeraie, 7,8 M MAD',
      },
      {
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=700&h=500&fit=crop',
        caption: 'Appartement de prestige — Hivernage',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Pierre-Antoine Marchand',
        authorInitials: 'PM',
        rating: 5,
        date: '5 mai 2024',
        text: "Nadia est tout simplement exceptionnelle. Résidant à Paris, j'ai acheté mon riad à Marrakech sans jamais me sentir perdu. Elle a géré la visite en visio, la négociation, le notaire, et la remise des clés. 5 étoiles sans hésitation.",
        projectType: 'Achat riad',
      },
      {
        id: 'r2',
        author: 'Sarah Al-Mansouri',
        authorInitials: 'SA',
        rating: 5,
        date: '14 mars 2024',
        text: "Professionnelle, disponible, de très bon conseil sur la rentabilité locative. Elle connaît le marché marrakchi mieux que quiconque. Notre villa est louée à 95% depuis l'achat.",
        projectType: 'Villa Palmeraie',
      },
      {
        id: 'r3',
        author: 'Thierry Dupont',
        authorInitials: 'TD',
        rating: 5,
        date: '28 janvier 2024',
        text: "Deuxième transaction avec Nadia, toujours impeccable. Honnête, réactive, et son réseau de contacts est précieux pour trouver les belles opportunités avant qu'elles soient en ligne.",
        projectType: 'Appartement Guéliz',
      },
    ],
  },

  {
    slug: 'mehdi-tazi-diagnostic',
    name: 'Mehdi Tazi',
    title: 'Expert en diagnostic immobilier',
    category: 'diagnostiqueur',
    city: 'Casablanca',
    district: 'Sidi Maârouf',
    bio: "Expert certifié en diagnostic immobilier, Mehdi Tazi réalise l'ensemble des diagnostics réglementaires requis au Maroc pour les transactions et mises en location. Avec plus de 1 240 diagnostics réalisés en 10 ans, il intervient dans tout le Grand Casablanca sous 48h chrono. Ses rapports détaillés et illustrés sont reconnus par les études notariales et les agences partenaires pour leur clarté et leur exactitude. Il utilise des équipements de mesure de dernière génération (thermographie infrarouge, analyseur de réseau électrique, caméra d'inspection).",
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1400&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 203,
    responseTime: 'Répond sous 4h',
    isVerified: true,
    isPremium: false,
    services: ['Diagnostic performance énergétique', 'Diagnostic électrique', 'Diagnostic plomberie', 'Inspection structure', 'Rapport complet pré-vente'],
    priceInfo: 'À partir de 800 MAD',
    completedProjects: 1240,
    yearsExperience: 10,
    languages: ['Français', 'Arabe'],
    specializations: ['Bâtiments résidentiels', 'Immeubles anciens', 'Villas & appartements'],
    certifications: ['Certification diagnostiqueur immobilier CNRNI', 'Habilitation thermographie IR niveau 1', 'Assuré RC professionnelle'],
    availability: 'disponible',
    phone: '+212 6 63 XX XX XX',
    email: 'mehdi.tazi.diagnostic@gmail.com',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=700&h=500&fit=crop',
        caption: 'Inspection structure — immeuble années 80',
      },
      {
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=500&fit=crop',
        caption: 'Diagnostic électrique complet — villa Ain Diab',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Fouad Benchekroun',
        authorInitials: 'FB',
        rating: 5,
        date: '12 avril 2024',
        text: "Mehdi est venu le lendemain de mon appel, rapport livré en 24h. Son diagnostic a révélé un défaut d'isolation que le vendeur n'avait pas déclaré. Grâce à lui, j'ai négocié 180 000 MAD de rabais. Indispensable avant tout achat.",
        projectType: 'Diagnostic pré-achat',
      },
      {
        id: 'r2',
        author: 'Imane Benali',
        authorInitials: 'IB',
        rating: 5,
        date: '20 février 2024',
        text: "Très sérieux, équipement professionnel, rapport très clair avec photos et recommandations priorisées. Mon notaire a été impressionné par la qualité du document.",
        projectType: 'Rapport complet pré-vente',
      },
      {
        id: 'r3',
        author: 'Khalid Naciri',
        authorInitials: 'KN',
        rating: 4,
        date: '5 janvier 2024',
        text: "Bon diagnostiqueur, ponctuel et professionnel. Le rapport mériterait un peu plus de détail sur les recommandations chiffrées mais la qualité globale est là.",
        projectType: 'Diagnostic électrique',
      },
    ],
  },

  {
    slug: 'sara-idrissi-architecte',
    name: 'Sara Idrissi',
    title: 'Architecte DPLG',
    category: 'architecte',
    city: 'Casablanca',
    district: 'Californie',
    bio: "Architecte DPLG diplômée de l'École Nationale d'Architecture de Rabat et de l'ENSA de Paris-Belleville, Sara Idrissi dirige un cabinet reconnu pour la qualité de ses réalisations résidentielles et la maîtrise irréprochable des délais. Spécialisée dans la rénovation haut de gamme et les extensions de villas, elle intègre dès la phase d'esquisse les contraintes structurelles, réglementaires et esthétiques. Elle a obtenu le permis de construire de 94 projets résidentiels sans un seul recours, et collabore avec un réseau d'entrepreneurs de confiance pour un suivi de chantier rigoureux.",
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1400&h=500&fit=crop',
    rating: 4.9,
    reviewCount: 61,
    responseTime: 'Répond sous 24h',
    isVerified: true,
    isPremium: true,
    services: ['Conception & maîtrise d\'œuvre', 'Rénovation haut de gamme', 'Extension de villa', 'Permis de construire', 'Suivi de chantier'],
    priceInfo: 'À partir de 5 000 MAD',
    completedProjects: 94,
    yearsExperience: 14,
    languages: ['Français', 'Arabe', 'Anglais'],
    specializations: ['Résidentiel premium', 'Rénovation & extension', 'Architecture bioclimatique'],
    certifications: ['DPLG Ordre des Architectes Maroc', 'Membre UMAR', 'Certification HQE bâtiment durable'],
    availability: 'sur_rdv',
    phone: '+212 6 64 XX XX XX',
    email: 'contact@idrissi-architecture.ma',
    website: 'www.idrissi-architecture.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=700&h=500&fit=crop',
        caption: 'Rénovation complète — villa Californie, Casablanca',
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Extension R+1 — Ain Diab',
      },
      {
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=700&h=500&fit=crop',
        caption: 'Design intérieur — appartement neuf Anfa',
      },
      {
        url: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=700&h=500&fit=crop',
        caption: 'Villa contemporaine livrée — CFC',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Adil Bensalah',
        authorInitials: 'AB',
        rating: 5,
        date: '8 mai 2024',
        text: "Sara a transformé notre villa des années 90 en une maison contemporaine lumineuse que nous ne reconnaissons plus. Chaque détail a été pensé : circulation, lumière naturelle, matériaux. Chantier livré à la semaine près.",
        projectType: 'Rénovation villa',
      },
      {
        id: 'r2',
        author: 'Myriam Kabbaj',
        authorInitials: 'MK',
        rating: 5,
        date: '14 février 2024',
        text: "Professionnalisme absolu. Sara écoute, propose, défend ses choix avec arguments techniques solides. Notre permis de construire obtenu en 6 semaines. Je ne ferai aucun projet sans elle.",
        projectType: 'Extension + permis',
      },
      {
        id: 'r3',
        author: 'Yassine El Khatib',
        authorInitials: 'YE',
        rating: 5,
        date: '30 octobre 2023',
        text: "Architecte de talent et femme de parole. Budget maîtrisé, délais tenus, rendu bluffant. Son réseau d'entrepreneurs est excellent et fait la différence sur le suivi de chantier.",
        projectType: 'Conception villa neuve',
      },
    ],
  },

  {
    slug: 'karim-benjelloun-architecte',
    name: 'Karim Benjelloun',
    title: 'Architecte & designer d\'intérieur',
    category: 'architecte',
    city: 'Marrakech',
    district: 'Hivernage',
    bio: "Architecte et designer d'intérieur installé à Marrakech depuis 16 ans, Karim Benjelloun est réputé pour sa maîtrise des arts décoratifs marocains traditionnels (zelliges, tadelakt, moucharabiehs) conjugués à une esthétique contemporaine épurée. Formé à l'ENA de Rabat puis à l'ENSAD de Paris, il a restauré 78 riads et villas, souvent pour des clients européens et du Golfe souhaitant allier authenticité et confort moderne. Ses projets ont été publiés dans AD Maroc, Vogue Living et The Design Files.",
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1400&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 45,
    responseTime: 'Répond sous 48h',
    isVerified: true,
    isPremium: true,
    services: ['Restauration de riad', 'Design intérieur', 'Architecture de villa', 'Direction artistique', 'Sourcing artisanat'],
    priceInfo: 'À partir de 8 000 MAD',
    completedProjects: 78,
    yearsExperience: 16,
    languages: ['Français', 'Arabe', 'Anglais', 'Italien'],
    specializations: ['Riads & patrimoine', 'Design contemporain marocain', 'Clientèle internationale'],
    certifications: ['DPLG Ordre des Architectes', 'Membre ADIM', 'Publications AD Maroc & Vogue Living'],
    availability: 'sur_rdv',
    phone: '+212 6 65 XX XX XX',
    email: 'k.benjelloun@studio-marrakech.com',
    website: 'www.studio-benjelloun.com',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=700&h=500&fit=crop',
        caption: 'Riad restauré 8 suites — Médina de Marrakech',
      },
      {
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=700&h=500&fit=crop',
        caption: 'Villa contemporaine — Palmeraie',
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Suite principale — Riad Hivernage',
      },
      {
        url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&h=500&fit=crop',
        caption: 'Cuisine tadelakt & zellige — Riad Bab Doukkala',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Charlotte de Villiers',
        authorInitials: 'CV',
        rating: 5,
        date: '22 avril 2024',
        text: "Karim a transformé notre riad délabré en un bijou. Chaque centimètre est pensé, les artisans qu'il sollicite sont des maîtres dans leur art. Notre riad loué sur Airbnb affiche un taux d'occupation de 89%. Merci.",
        projectType: 'Restauration riad',
      },
      {
        id: 'r2',
        author: 'Ahmed Al-Rashidi',
        authorInitials: 'AR',
        rating: 5,
        date: '11 janvier 2024',
        text: "Un designer qui comprend la culture marocaine dans sa profondeur et sait l'interpréter avec modernité. Notre villa de la Palmeraie est exactement ce que nous imaginions — en mieux.",
        projectType: 'Villa Palmeraie',
      },
      {
        id: 'r3',
        author: 'Isabelle Fontaine',
        authorInitials: 'IF',
        rating: 5,
        date: '3 octobre 2023',
        text: "Travail absolument magnifique. Les délais ont été tenus malgré un projet très complexe. Karim est aussi un excellent chef de projet : il coordonne les artisans avec autorité et bienveillance.",
        projectType: 'Riad Médina',
      },
    ],
  },

  {
    slug: 'renovation-pro-maroc',
    name: 'Rénovation Pro Maroc',
    title: 'Entreprise générale de rénovation',
    category: 'entrepreneur',
    city: 'Casablanca',
    district: 'Ain Sebaâ',
    bio: "Avec une équipe de 45 artisans qualifiés opérant sur le Grand Casablanca et Rabat, Rénovation Pro Maroc est spécialisée dans la rénovation complète d'appartements et de villas depuis 15 ans. Devis gratuit sous 24h, garantie décennale sur tous les travaux de structure. L'entreprise gère l'intégralité du chantier : gros œuvre, électricité aux normes NF, plomberie, carrelage, peinture et menuiserie. 620 chantiers livrés avec un taux de satisfaction client de 94 %. Suivi de chantier en temps réel via application mobile.",
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=1400&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 189,
    responseTime: 'Répond sous 24h',
    isVerified: true,
    isPremium: false,
    services: ['Rénovation complète', 'Électricité & plomberie', 'Carrelage & revêtements', 'Peinture & enduits', 'Menuiserie aluminium'],
    priceInfo: 'À partir de 1 500 MAD/m²',
    completedProjects: 620,
    yearsExperience: 15,
    languages: ['Français', 'Arabe'],
    specializations: ['Rénovation résidentielle', 'Second œuvre', 'Finitions haut de gamme'],
    certifications: ['CNSS entreprise', 'Garantie décennale assurée', 'RC professionnelle AXA'],
    availability: 'disponible',
    phone: '+212 5 22 XX XX XX',
    email: 'contact@renovationpro.ma',
    website: 'www.renovationpro.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Rénovation totale — appartement 120 m² Maarif',
      },
      {
        url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=700&h=500&fit=crop',
        caption: 'Salle de bain refaite — villa Ain Diab',
      },
      {
        url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&h=500&fit=crop',
        caption: 'Cuisine rénovée — appartement Racine',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Tariq Benomar',
        authorInitials: 'TB',
        rating: 5,
        date: '30 mars 2024',
        text: "Rénovation complète de notre appartement de 110 m² en 6 semaines chrono. Équipe sérieuse, propre, respectueuse. Le suivi via leur app était très pratique. Rendu impeccable.",
        projectType: 'Rénovation complète',
      },
      {
        id: 'r2',
        author: 'Houda Lamrani',
        authorInitials: 'HL',
        rating: 4,
        date: '10 février 2024',
        text: "Bon rapport qualité/prix, équipe compétente. Un petit retard sur la livraison de la cuisine mais ils ont compensé avec un geste commercial. Je referai appel à eux.",
        projectType: 'Rénovation cuisine & SDB',
      },
      {
        id: 'r3',
        author: 'Aziz Tahiri',
        authorInitials: 'AT',
        rating: 5,
        date: '22 novembre 2023',
        text: "J'ai rénové 3 appartements avec eux pour de la location meublée. À chaque fois dans les délais, dans le budget, et les locataires sont ravis de la qualité des finitions.",
        projectType: 'Rénovation locative x3',
      },
    ],
  },

  {
    slug: 'atlas-build-marrakech',
    name: 'Atlas Build',
    title: 'Entrepreneur général — Construction & Rénovation',
    category: 'entrepreneur',
    city: 'Marrakech',
    district: 'Route de Fès',
    bio: "Entrepreneur général basé à Marrakech depuis 20 ans, Atlas Build est spécialisé dans la construction neuve et la rénovation de riads, villas et maisons d'hôtes. L'équipe de maîtres artisans perpétue les techniques traditionnelles du bâtiment marocain — maçonnerie en pisé, finitions en tadelakt mat et brillant, zelliges mosaïques — dans le respect des normes parasismiques Zone 3 en vigueur. 143 projets menés à bien, dont plusieurs primés par la Région Marrakech-Safi pour la préservation du patrimoine architectural.",
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1400&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 67,
    responseTime: 'Répond sous 24h',
    isVerified: true,
    isPremium: false,
    services: ['Construction neuve', 'Maçonnerie traditionnelle', 'Tadelakt & zellige', 'Rénovation riad', 'Pisé & torchis'],
    priceInfo: 'Sur devis',
    completedProjects: 143,
    yearsExperience: 20,
    languages: ['Arabe', 'Français'],
    specializations: ['Techniques traditionnelles marocaines', 'Construction pisé', 'Restauration patrimoine'],
    certifications: ['CNSS entreprise', 'Certification artisanat marocain', 'Primé Région Marrakech-Safi 2022'],
    availability: 'sur_rdv',
    phone: '+212 5 24 XX XX XX',
    email: 'contact@atlasbuild.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=700&h=500&fit=crop',
        caption: 'Riad construit en pisé — Médina',
      },
      {
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=700&h=500&fit=crop',
        caption: 'Villa contemporaine construite — Palmeraie',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Dominique Leclerc',
        authorInitials: 'DL',
        rating: 5,
        date: '18 mars 2024',
        text: "Atlas Build a construit notre maison d'hôtes de A à Z. Le tadelakt est d'une qualité que je n'avais jamais vue, les zelliges posés avec une précision d'orfèvre. Chantier de 14 mois, livré à l'heure.",
        projectType: 'Construction maison d\'hôtes',
      },
      {
        id: 'r2',
        author: 'Mustapha Belkadi',
        authorInitials: 'MB',
        rating: 5,
        date: '6 décembre 2023',
        text: "Equipe de vrais artisans. Ils ont restauré les murs en pisé de notre riad avec un savoir-faire rare. Les autorités de la Médina ont reconnu la qualité du travail et nous ont félicités.",
        projectType: 'Restauration riad Médina',
      },
    ],
  },

  {
    slug: 'maitre-fatima-berrada',
    name: 'Maître Fatima Berrada',
    title: 'Avocate en droit immobilier',
    category: 'avocat',
    city: 'Casablanca',
    district: 'Gauthier',
    bio: "Avocate au Barreau de Casablanca depuis 19 ans, Maître Fatima Berrada intervient exclusivement en droit immobilier : contentieux locatif, litiges de copropriété, recouvrement de loyers impayés, nullités de vente et expropriations. Elle conseille également des promoteurs immobiliers pour la structuration juridique de leurs projets et la rédaction de contrats de réservation conformes. Sa réputation de rigueur et de fermeté lui vaut d'être régulièrement recommandée par les études notariales et les agences immobilières de la place.",
    avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=1400&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 38,
    responseTime: 'Répond sous 48h',
    isVerified: true,
    isPremium: false,
    services: ['Contentieux locatif', 'Litiges copropriété', 'Recouvrement loyers', 'Nullité de vente', 'Conseil promoteur'],
    priceInfo: 'À partir de 3 500 MAD',
    completedProjects: 210,
    yearsExperience: 19,
    languages: ['Français', 'Arabe'],
    specializations: ['Contentieux immobilier', 'Droit locatif', 'Droit de la copropriété'],
    certifications: ['Barreau de Casablanca', 'Spécialisation droit immobilier ENCG', 'Médiatrice agréée'],
    availability: 'sur_rdv',
    phone: '+212 5 22 XX XX XX',
    email: 'f.berrada@avocat-berrada.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=700&h=500&fit=crop',
        caption: 'Cabinet juridique — Gauthier, Casablanca',
      },
      {
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&h=500&fit=crop',
        caption: 'Conseil juridique promoteur immobilier',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Khalil Amrani',
        authorInitials: 'KA',
        rating: 5,
        date: '25 avril 2024',
        text: "Maître Berrada a récupéré 18 mois de loyers impayés en moins de 4 mois, procédure incluse. Efficacité redoutable, communication claire sur chaque étape. Indispensable si vous louez.",
        projectType: 'Recouvrement loyers',
      },
      {
        id: 'r2',
        author: 'Zineb Hajji',
        authorInitials: 'ZH',
        rating: 5,
        date: '9 février 2024',
        text: "Elle nous a sauvés d'une vente frauduleuse sur plan. Son analyse du contrat de réservation a révélé des clauses abusives. Procès gagné, remboursement obtenu. Merci infiniment.",
        projectType: 'Nullité de vente VEFA',
      },
      {
        id: 'r3',
        author: 'Rachid Kettani',
        authorInitials: 'RK',
        rating: 5,
        date: '14 novembre 2023',
        text: "Très bonne avocate, rigoureuse et disponible. Elle n'hésite pas à appeler le week-end si l'affaire l'exige. Notre litige de copropriété résolu à l'amiable grâce à sa médiation.",
        projectType: 'Litige copropriété',
      },
    ],
  },

  {
    slug: 'amine-lahlou-photo',
    name: 'Amine Lahlou',
    title: 'Photographe immobilier & vidéaste',
    category: 'photographe',
    city: 'Casablanca',
    district: 'Maârif',
    bio: "Photographe immobilier certifié Matterport et pilote de drone DGAC, Amine Lahlou produit des visuels haut de gamme qui valorisent chaque bien immobilier : photographie grand angle, home staging virtuel, visite 360° interactive et prises de vue aériennes par drone pour les extérieurs, toitures-terrasses et jardins. Ses clichés ont contribué à des ventes en moyenne 2,4 fois plus rapides sur les plateformes partenaires. Il intervient le jour même pour les biens du Grand Casablanca.",
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=1400&h=500&fit=crop',
    rating: 4.9,
    reviewCount: 156,
    responseTime: 'Répond sous 2h',
    isVerified: true,
    isPremium: true,
    services: ['Photos grand angle HDR', 'Visite virtuelle 360°', 'Drone & vue aérienne', 'Home staging virtuel', 'Vidéo cinématique'],
    priceInfo: 'À partir de 1 200 MAD',
    completedProjects: 890,
    yearsExperience: 9,
    languages: ['Français', 'Arabe', 'Anglais'],
    specializations: ['Photographie immobilière', 'Visite Matterport 3D', 'Drone autorisé CAA'],
    certifications: ['Certification Matterport Pro', 'Licence pilote drone DGAC', 'Membre UPCP'],
    availability: 'disponible',
    phone: '+212 6 66 XX XX XX',
    email: 'amine@lahlou-photo.ma',
    website: 'www.lahlou-photo.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=700&h=500&fit=crop',
        caption: 'Séance appartement terrasse — Racine',
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Villa Ain Diab — drone & intérieur',
      },
      {
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=700&h=500&fit=crop',
        caption: 'Séance prestige — penthouse Anfa',
      },
      {
        url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&h=500&fit=crop',
        caption: 'Cuisine architecte — visite 360°',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Samir Tahri',
        authorInitials: 'ST',
        rating: 5,
        date: '6 mai 2024',
        text: "Amine a shooté mon appartement un vendredi soir, j'avais les photos le dimanche matin. Le bien était mis en ligne le lundi, vendu le mercredi. Ses photos font toute la différence.",
        projectType: 'Reportage vente',
      },
      {
        id: 'r2',
        author: 'Laila Bennis',
        authorInitials: 'LB',
        rating: 5,
        date: '17 mars 2024',
        text: "La visite virtuelle 3D de ma villa a généré 12 demandes de visite en 48h. Amine est rapide, discret, et son œil pour la lumière est exceptionnel. Très recommandé.",
        projectType: 'Visite 360° + drone',
      },
      {
        id: 'r3',
        author: 'Nicolas Blanchard',
        authorInitials: 'NB',
        rating: 5,
        date: '22 janvier 2024',
        text: "Meilleur photographe immobilier de Casablanca selon moi. Après son passage, mon appartement ressemblait à une page de magazine. Prix très raisonnable pour la qualité.",
        projectType: 'Reportage location meublée',
      },
    ],
  },

  {
    slug: 'demenagement-express-maroc',
    name: 'Déménagement Express Maroc',
    title: 'Spécialiste déménagement résidentiel & professionnel',
    category: 'demenageur',
    city: 'Casablanca',
    district: 'Sidi Moumen',
    bio: "Leader régional du déménagement résidentiel et professionnel, Déménagement Express dispose d'une flotte de 22 véhicules et d'équipes spécialisées dans le conditionnement et le transport sécurisé de mobilier, objets d'art et équipements fragiles. Couverture nationale : Casablanca, Marrakech, Rabat, Tanger et toutes les grandes villes. Stockage sécurisé (gardiennage 24h, caméras) disponible à la semaine ou au mois. Assurance tous risques incluse dans chaque devis.",
    avatar: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=200&h=200&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1400&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 312,
    responseTime: 'Répond sous 1h',
    isVerified: true,
    isPremium: false,
    services: ['Déménagement local', 'Déménagement inter-villes', 'Déménagement international', 'Stockage sécurisé', 'Emballage professionnel'],
    priceInfo: 'À partir de 1 800 MAD',
    completedProjects: 2100,
    yearsExperience: 12,
    languages: ['Arabe', 'Français'],
    specializations: ['Résidentiel', 'Professionnel & bureaux', 'Objets d\'art & fragiles'],
    certifications: ['CNSS entreprise', 'Assurance RC & tous risques AXA', 'Agrément transport marchandises'],
    availability: 'disponible',
    phone: '+212 5 22 XX XX XX',
    email: 'devis@demenagement-express.ma',
    website: 'www.demenagement-express.ma',
    portfolio: [
      {
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=500&fit=crop',
        caption: 'Déménagement villa — Ain Diab vers Marrakech',
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop',
        caption: 'Installation appartement neuf — CFC',
      },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Yasmine Tahir',
        authorInitials: 'YT',
        rating: 5,
        date: '2 mai 2024',
        text: "Déménagement Casablanca → Rabat avec une villa complète. Rien de cassé, tout emballé avec soin, camion propre et équipe polie. Livraison à l'heure. Je recommande vivement.",
        projectType: 'Déménagement inter-villes',
      },
      {
        id: 'r2',
        author: 'Driss Lamghari',
        authorInitials: 'DL',
        rating: 4,
        date: '15 mars 2024',
        text: "Bon service, équipe efficace. Un carton qui s'est ouvert en route mais rien de cassé. Prix compétitif et très bon accueil téléphonique.",
        projectType: 'Déménagement local',
      },
      {
        id: 'r3',
        author: 'Marie-Claire Goffin',
        authorInitials: 'MG',
        rating: 5,
        date: '8 janvier 2024',
        text: "Déménagement d'un appartement meublé Casablanca → retour en France via Tanger. Packaging parfait pour le transport maritime. Aucune casse, parfaitement organisé.",
        projectType: 'Déménagement international',
      },
    ],
  },
]

export function getPresataireBySlug(slug: string): Prestataire | undefined {
  return PRESTATAIRES.find((p) => p.slug === slug)
}

export function getPresataireCardData(): PresataireCardData[] {
  return PRESTATAIRES.map(({ slug, name, title, category, city, district, avatar, coverImage, rating, reviewCount, responseTime, isVerified, isPremium, services, priceInfo, completedProjects, availability }) => ({
    slug, name, title, category, city, district, avatar, coverImage, rating, reviewCount, responseTime, isVerified, isPremium, services, priceInfo, completedProjects, availability,
  }))
}

export function getRelatedPrestataires(slug: string, category: string, limit = 4): PresataireCardData[] {
  const all = getPresataireCardData()
  const same = all.filter((p) => p.slug !== slug && p.category === category)
  if (same.length >= limit) return same.slice(0, limit)
  const others = all.filter((p) => p.slug !== slug && p.category !== category)
  return [...same, ...others].slice(0, limit)
}
