import type { Produit, ProduitCardData } from '@/types/produit'

export const PRODUITS: Produit[] = [
  // ── SALON ──────────────────────────────────────────────────────
  {
    slug: 'canape-angle-velours-emeraude',
    name: "Canapé d'angle velours émeraude",
    category: 'salon',
    style: 'moderne',
    brand: 'Kitea Déco',
    city: 'Casablanca',
    price: 8500,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&h=700&fit=crop',
    ],
    description: "Canapé d'angle 5 places en velours émeraude avec pieds en métal doré. Structure en contreplaqué multiplis avec ressorts ensachés pour un confort optimal. Revêtement velours haut de gamme résistant à l'usure. Idéal pour les grands salons.",
    dimensions: '285 × 185 × 82 cm',
    material: 'Velours 100% polyester, pieds métal doré',
    colors: ['Émeraude', 'Bleu nuit', 'Gris anthracite', 'Camel'],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 34,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000001',
    features: ['5 places', 'Pieds métal doré', 'Velours résistant', 'Montage inclus'],
  },
  {
    slug: 'table-basse-marbre-blanc',
    name: 'Table basse plateau marbre blanc',
    category: 'salon',
    style: 'contemporain',
    brand: 'Artisan Casa',
    city: 'Casablanca',
    price: 3200,
    oldPrice: 3800,
    images: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
    ],
    description: "Table basse au design épuré, plateau en marbre blanc veiné de Carrare posé sur un cadre en métal noir mat. Fabrication artisanale locale. Résistante aux chocs et facile d'entretien. La pièce maîtresse de votre salon.",
    dimensions: '120 × 60 × 42 cm',
    material: 'Marbre naturel, structure métal noir mat',
    colors: ['Blanc Carrare / Métal noir'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 19,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000002',
    features: ['Marbre naturel', 'Fabrication locale', 'Livraison et montage inclus'],
  },
  {
    slug: 'fauteuil-pivotant-cuir-camel',
    name: 'Fauteuil pivotant cuir camel',
    category: 'salon',
    style: 'moderne',
    brand: 'Mobilier Plus',
    city: 'Casablanca',
    price: 4200,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
    ],
    description: "Fauteuil de lecture pivotant à 360° en cuir véritable camel. Assise et dossier rembourrés en mousse haute résilience. Base étoile en acier inoxydable poli. Un classique du design scandinave réinterprété.",
    dimensions: '75 × 78 × 82 cm',
    material: 'Cuir véritable, base acier inoxydable',
    colors: ['Camel', 'Cognac', 'Bordeaux', 'Noir'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 28,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000003',
    features: ['Pivotant 360°', 'Cuir véritable', 'Hauteur réglable'],
  },
  {
    slug: 'poufs-cuir-marrakchi-lot-2',
    name: 'Poufs cuir Marrakchi (lot de 2)',
    category: 'salon',
    style: 'marocain',
    brand: 'Artisanat Marrakech',
    city: 'Marrakech',
    price: 1850,
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&h=700&fit=crop',
    ],
    description: "Authentiques poufs marocains en cuir tannée végétale de Marrakech, cousus et brodés à la main par des artisans de la Médina. Rempli de coton naturel. Chaque pièce est unique. Disponibles brodés ou unis.",
    dimensions: 'Ø 40 × 30 cm chacun',
    material: 'Cuir tannée végétale, coton naturel',
    colors: ['Miel', 'Bordeaux', 'Vert olive', 'Noir', 'Terracotta'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 87,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000004',
    features: ['Artisanat Médina', 'Cuir tanné végétal', 'Brodé main', 'Pièce unique'],
  },
  {
    slug: 'bibliotheque-metal-bois-manguier',
    name: 'Bibliothèque métal & bois de manguier',
    category: 'salon',
    style: 'industriel',
    brand: 'Déco Design',
    city: 'Rabat',
    price: 5600,
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&h=700&fit=crop',
    ],
    description: "Grande bibliothèque style industriel en métal noir mat et tablettes en bois de manguier massif huilé. 6 niveaux de rangement, montage simple avec notice illustrée. Robuste et intemporelle.",
    dimensions: '180 × 90 × 35 cm',
    material: 'Métal noir mat, bois de manguier huilé',
    colors: ['Métal noir / Manguier naturel', 'Métal rouille / Manguier foncé'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 12,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 37 XX XX XX',
    whatsapp: '+212661000005',
    features: ['6 niveaux', 'Bois massif', 'Notice montage incluse'],
  },

  // ── CHAMBRE ───────────────────────────────────────────────────
  {
    slug: 'lit-plateforme-noyer-160',
    name: 'Lit plateforme 160×200 en noyer',
    category: 'chambre',
    style: 'scandinave',
    brand: 'Artisan Menuisier',
    city: 'Casablanca',
    price: 7800,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&h=700&fit=crop',
    ],
    description: "Lit plateforme bas en noyer massif certifié FSC. Design épuré inspiré du mobilier scandinave. Tête de lit intégrée, lattes de sommier incluses. Fabriqué à Casablanca par un maître ébéniste. Personnalisable en 160×200 ou 180×200.",
    dimensions: '160 × 200 cm (couchage)',
    material: 'Noyer massif certifié FSC',
    colors: ['Noyer naturel', 'Noyer foncé'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 45,
    deliveryTime: '14 à 21 jours',
    phone: '+212 6 64 XX XX XX',
    whatsapp: '+212661000006',
    features: ['Bois massif FSC', 'Lattes incluses', 'Fabrication locale', 'Sur-mesure possible'],
  },
  {
    slug: 'tete-lit-capitonnee-velours',
    name: 'Tête de lit capitonnée velours bleu nuit',
    category: 'chambre',
    style: 'contemporain',
    brand: 'Literie Maroc',
    city: 'Casablanca',
    price: 3200,
    images: [
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&h=700&fit=crop',
    ],
    description: "Tête de lit capitonnée en velours côtelé bleu nuit avec boutons dorés. Structure en bois massif, rembourrage en mousse haute densité 40 kg/m³. Fixation murale facile avec kit inclus. Compatible 140, 160 et 180 cm.",
    dimensions: '160 × 120 × 12 cm',
    material: 'Velours côtelé, bois massif, mousse HD',
    colors: ['Bleu nuit', 'Vert sauge', 'Ocre', 'Gris perle'],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 22,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000007',
    features: ['Capitonnée boutons dorés', 'Kit fixation inclus', 'Plusieurs tailles'],
  },
  {
    slug: 'miroir-arche-doree-180',
    name: 'Miroir arche dorée 180 cm',
    category: 'chambre',
    style: 'contemporain',
    brand: 'Déco Salon',
    city: 'Marrakech',
    price: 2400,
    oldPrice: 2900,
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&h=700&fit=crop',
    ],
    description: "Grand miroir en arche au cadre en métal doré brossé. Verre de 5 mm traitement anti-humidité. Design sobre et élégant qui agrandit visuellement l'espace. Peut être posé au sol ou fixé au mur.",
    dimensions: '60 × 180 cm',
    material: 'Verre 5 mm, cadre métal doré brossé',
    colors: ['Doré brossé', 'Noir mat'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 156,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000008',
    features: ['180 cm de hauteur', 'Verre anti-humidité', 'Sol ou mural'],
  },
  {
    slug: 'armoire-dressing-3-portes',
    name: 'Armoire dressing 3 portes miroir',
    category: 'chambre',
    style: 'moderne',
    brand: 'Casa Mobilier',
    city: 'Casablanca',
    price: 6400,
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&h=700&fit=crop',
    ],
    description: "Armoire dressing 3 portes dont 2 portes miroir coulissantes. Structure en panneau MDF laqué blanc. Intérieur : 2 penderies, 4 étagères, 2 tiroirs. Gain de place optimal pour les chambres de moins de 15 m².",
    dimensions: '240 × 210 × 60 cm',
    material: 'MDF laqué blanc, miroir 4 mm',
    colors: ['Blanc laqué', 'Gris clair'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 31,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000009',
    features: ['2 portes miroir', 'Coulissantes', 'Montage professionnel inclus'],
  },

  // ── CUISINE ───────────────────────────────────────────────────
  {
    slug: 'ilot-cuisine-bois-massif',
    name: 'Îlot de cuisine bois massif',
    category: 'cuisine',
    style: 'moderne',
    brand: 'Cuisine Pro',
    city: 'Casablanca',
    price: 9800,
    images: [
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&h=700&fit=crop',
    ],
    description: "Îlot central de cuisine en chêne massif huilé avec plan de travail en quartz blanc. 3 tiroirs intégrés, espace ouvert pour les paniers de rangement. Finition bord épais 4 cm. Sur-mesure possible selon vos dimensions.",
    dimensions: '150 × 90 × 90 cm',
    material: 'Chêne massif huilé, plan quartz blanc',
    colors: ['Chêne naturel / Quartz blanc', 'Noyer foncé / Quartz gris'],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 24,
    deliveryTime: '21 à 30 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000010',
    features: ['Plan quartz', '3 tiroirs', 'Sur-mesure possible', 'Pose incluse'],
  },
  {
    slug: 'bar-comptoir-tabourets',
    name: 'Bar comptoir + 2 tabourets inclus',
    category: 'cuisine',
    style: 'industriel',
    brand: 'Mobilier Bar',
    city: 'Rabat',
    price: 3800,
    images: [
      'https://images.unsplash.com/photo-1537726235470-8504e3beef77?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&h=700&fit=crop',
    ],
    description: "Bar comptoir style industriel en acier et bois de pin avec 2 tabourets hauts assortis. Idéal pour séparer cuisine ouverte et salon. Plateau en bois brûlé (finition Shou Sugi Ban) sur structure métal noir.",
    dimensions: '120 × 60 × 100 cm (bar)',
    material: 'Pin massif Shou Sugi Ban, structure acier',
    colors: ['Bois brûlé / Métal noir'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.3,
    reviewCount: 9,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 37 XX XX XX',
    whatsapp: '+212661000011',
    features: ['2 tabourets inclus', 'Bois Shou Sugi Ban', 'Séparation cuisine/salon'],
  },
  {
    slug: 'vaisselier-industriel-6-tablettes',
    name: 'Vaisselier industriel 6 tablettes',
    category: 'cuisine',
    style: 'industriel',
    brand: 'Bois & Métal',
    city: 'Casablanca',
    price: 4200,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&h=700&fit=crop',
    ],
    description: "Vaisselier ouvert style industriel avec 6 tablettes en bois d'acacia massif sur structure acier brossé. Convient pour la vaisselle, livres de cuisine, plantes. Conception ouverte pour un accès facile et un visuel aéré.",
    dimensions: '90 × 200 × 30 cm',
    material: 'Acacia massif, acier brossé',
    colors: ['Acacia naturel / Acier brossé'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 17,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000012',
    features: ['6 tablettes', 'Bois acacia massif', 'Design ouvert'],
  },

  // ── SALLE DE BAIN ─────────────────────────────────────────────
  {
    slug: 'meuble-vasque-tadelakt-gris',
    name: 'Meuble vasque tadelakt gris 80 cm',
    category: 'salle-de-bain',
    style: 'marocain',
    brand: 'Artisan Fès',
    city: 'Fès',
    price: 4800,
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&h=700&fit=crop',
    ],
    description: "Meuble vasque en tadelakt gris ardoise, technique ancestrale de la maçonnerie marocaine. Étanche et résistant à la vapeur, le tadelakt est parfait pour la salle de bain. Vasque intégrée, 2 tiroirs en bois naturel, robinetterie non incluse.",
    dimensions: '80 × 50 × 85 cm',
    material: 'Tadelakt gris ardoise, bois de pin naturel',
    colors: ['Gris ardoise', 'Blanc cassé', 'Terracotta'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 33,
    deliveryTime: '14 à 21 jours',
    phone: '+212 5 35 XX XX XX',
    whatsapp: '+212661000013',
    features: ['Tadelakt imperméable', 'Artisanat Fès', '2 tiroirs', 'Sur-mesure possible'],
  },
  {
    slug: 'miroir-laiton-salle-de-bain',
    name: 'Miroir laiton doré salle de bain',
    category: 'salle-de-bain',
    style: 'contemporain',
    brand: 'Laiton Design',
    city: 'Marrakech',
    price: 1900,
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&h=700&fit=crop',
    ],
    description: "Miroir rond de salle de bain avec cadre en laiton doré vieilli. Traitement anti-buée intégré, fixation murale renforcée. S'associe parfaitement avec les robinetteries et accessoires en laiton pour une salle de bain cohérente.",
    dimensions: 'Ø 80 cm',
    material: 'Laiton doré vieilli, verre anti-buée',
    colors: ['Laiton doré vieilli', 'Laiton brossé'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 41,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000014',
    features: ['Anti-buée', 'Laiton vieilli', 'Fixation incluse'],
  },

  // ── DÉCORATION ────────────────────────────────────────────────
  {
    slug: 'tapis-beni-ouarain-200x300',
    name: 'Tapis Beni Ouarain 200×300',
    category: 'tapis-textiles',
    style: 'marocain',
    brand: 'Artisanat Amazigh',
    city: 'Marrakech',
    price: 3800,
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
    ],
    description: "Authentique tapis Beni Ouarain en laine naturelle de brebis des montagnes du Moyen-Atlas. Tissé à la main par des artisanes amazighes. Motifs géométriques traditionnels en noir sur fond ivoire. Chaque tapis est une pièce unique avec ses légères variations naturelles.",
    dimensions: '200 × 300 cm',
    material: 'Laine naturelle non teintée, chaîne coton',
    colors: ['Ivoire / Motifs noirs'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 203,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000015',
    features: ['Tissé main', 'Laine naturelle', 'Pièce unique', 'Berbère authentique'],
  },
  {
    slug: 'lanternes-cuivre-cisele-lot-3',
    name: 'Lanternes cuivre ciselé (lot de 3)',
    category: 'decoration',
    style: 'marocain',
    brand: 'Cuivre Artisan',
    city: 'Marrakech',
    price: 1200,
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&h=700&fit=crop',
    ],
    description: "Lot de 3 lanternes en cuivre martelé et ciselé à la main par des artisans de la Médina de Marrakech. Motifs géométriques berbères. Verres colorés : ambre, rouge et vert. Utilisables avec bougies chauffe-plat ou ampoules LED E14.",
    dimensions: 'S: 15cm · M: 22cm · L: 30cm (hauteur)',
    material: 'Cuivre martelé ciselé, verre coloré',
    colors: ['Cuivre naturel / Verres colorés'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 94,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000016',
    features: ['Lot de 3 tailles', 'Ciselé main', 'Compatible LED', 'Artisan Médina'],
  },
  {
    slug: 'tableau-abstrait-minimaliste',
    name: 'Tableau abstrait minimaliste 80×100',
    category: 'decoration',
    style: 'moderne',
    brand: 'Galerie Art Déco',
    city: 'Casablanca',
    price: 2600,
    oldPrice: 3200,
    images: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&h=700&fit=crop',
    ],
    description: "Peinture originale à l'acrylique sur toile de lin, technique couteau et pinceau large. Palette terracotta-ocre-beige inspirée des paysages du désert marocain. Pièce unique signée, livrée avec cadre flottant noir mat inclus.",
    dimensions: '80 × 100 cm',
    material: 'Acrylique sur toile de lin, cadre flottant bois',
    colors: ['Terracotta / Ocre / Beige', 'Bleu nuit / Or / Blanc'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 16,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000017',
    features: ['Pièce originale signée', 'Cadre inclus', 'Peinture acrylique'],
  },
  {
    slug: 'kilim-berbere-laine-naturelle',
    name: 'Kilim berbère laine naturelle 160×230',
    category: 'tapis-textiles',
    style: 'marocain',
    brand: 'Tissage Berbère',
    city: 'Marrakech',
    price: 2800,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&h=700&fit=crop',
    ],
    description: "Kilim plat tissé sur métier vertical par des femmes tisserandes du Haut Atlas. Laine teintée aux pigments naturels : grenade, henné, saffran et feuilles de noyer. Motifs losanges et chevrons traditionnels Azilal. Réversible.",
    dimensions: '160 × 230 cm',
    material: 'Laine teinture végétale, chaîne coton',
    colors: ['Naturel multicolore', 'Tons chauds terracotta'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.9,
    reviewCount: 78,
    deliveryTime: '5 à 7 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000018',
    features: ['Teintures végétales', 'Tissé main', 'Réversible', 'Azilal traditionnel'],
  },

  // ── LUMINAIRES ────────────────────────────────────────────────
  {
    slug: 'lustre-laiton-6-branches',
    name: 'Lustre suspendu laiton 6 branches',
    category: 'luminaires',
    style: 'marocain',
    brand: 'Artisan Laiton',
    city: 'Marrakech',
    price: 3600,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a35b7e5c3?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&h=700&fit=crop',
    ],
    description: "Lustre artisanal en laiton martelé à 6 bras. Chaque bras est orné de motifs géométriques islamiques perforés qui projettent des ombres décoratives sur les murs. Compatible ampoules E27 LED max 40W par bras. Câble textile réglable.",
    dimensions: 'Ø 70 × 45 cm (hors câble)',
    material: 'Laiton martelé, câble textile',
    colors: ['Laiton naturel', 'Laiton oxydé noir'],
    inStock: true,
    isNew: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 67,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000019',
    features: ['6 bras', 'Motifs perforés', 'Câble réglable', '6 × E27 max 40W'],
  },
  {
    slug: 'applique-zellige-bleu-fes',
    name: 'Applique murale zellige bleu de Fès',
    category: 'luminaires',
    style: 'marocain',
    brand: 'Zellige Déco',
    city: 'Fès',
    price: 1400,
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1513506003901-1e6a35b7e5c3?w=900&h=700&fit=crop',
    ],
    description: "Applique murale unique composée de tesselles de zellige bleues de Fès enchâssées dans une coupole en plâtre sculpt. Chaque applique est une pièce unique façonnée par un maître plâtrier. Diffuse une lumière chaude et tamisée.",
    dimensions: 'Ø 25 × 18 cm',
    material: 'Zellige de Fès, plâtre sculpté, laiton',
    colors: ['Bleu de Fès', 'Vert Bejmat', 'Blanc et or'],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 38,
    deliveryTime: '7 à 14 jours',
    phone: '+212 5 35 XX XX XX',
    whatsapp: '+212661000020',
    features: ['Pièce unique', 'Zellige de Fès', 'Plâtre sculpté', 'E14 max 25W'],
  },
  {
    slug: 'lampe-sol-bambou-naturel',
    name: 'Lampe sur pied bambou naturel',
    category: 'luminaires',
    style: 'boheme',
    brand: 'Eco Déco',
    city: 'Casablanca',
    price: 1650,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a35b7e5c3?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&h=700&fit=crop',
    ],
    description: "Grande lampe de sol en bambou naturel tressé main avec abat-jour en corde de jute. Pied stable lestable, câble tissu beige 2m. Ampoule vintage Edison E27 incluse. Idéale pour créer une ambiance chaleureuse et naturelle.",
    dimensions: '35 × 35 × 165 cm',
    material: 'Bambou naturel, corde de jute, câble tissu',
    colors: ['Naturel / Jute beige'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 19,
    deliveryTime: '3 à 5 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000021',
    features: ['Ampoule Edison incluse', 'Bambou durable', 'Câble tissu 2m'],
  },

  // ── TERRASSE ──────────────────────────────────────────────────
  {
    slug: 'salon-jardin-rotin-gris',
    name: 'Salon de jardin rotin gris 5 places',
    category: 'terrasse',
    style: 'moderne',
    brand: 'Outdoor Casa',
    city: 'Casablanca',
    price: 7200,
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&h=700&fit=crop',
    ],
    description: "Salon de jardin 5 places en rotin synthétique tressé gris anthracite sur structure aluminium. Coussinets inclus en tissu outdoor Sunbrella® résistant aux UV et à l'humidité. Table basse vitrée incluse. Résistant à toutes les intempéries.",
    dimensions: 'Canapé 2pl: 140cm · Fauteuils: 75cm · Table: 90×50cm',
    material: 'Rotin synthétique, aluminium, Sunbrella®',
    colors: ['Gris anthracite / Coussins écru', 'Noir / Coussins blanc'],
    inStock: true,
    isNew: false,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 28,
    deliveryTime: '14 à 21 jours',
    phone: '+212 5 22 XX XX XX',
    whatsapp: '+212661000022',
    features: ['Tissu Sunbrella®', 'Anti-UV', 'Table incluse', 'Structure aluminium'],
  },
  {
    slug: 'fontaine-murale-zellij-turquoise',
    name: 'Fontaine murale zellij turquoise',
    category: 'terrasse',
    style: 'marocain',
    brand: 'Art Zellij',
    city: 'Marrakech',
    price: 4200,
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&h=700&fit=crop',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&h=700&fit=crop',
    ],
    description: "Fontaine murale artisanale en zellij turquoise de Fès avec vasque en tadelakt blanc. Pompe silencieuse 12W incluse. Peut être utilisée en intérieur (salon, entrée) ou en extérieur (terrasse, patio, jardin). Fabrication entièrement à la main.",
    dimensions: '60 × 90 × 25 cm',
    material: 'Zellige de Fès, tadelakt, cuivre',
    colors: ['Turquoise / Blanc', 'Bleu de Fès / Ivoire'],
    inStock: true,
    isNew: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 44,
    deliveryTime: '14 à 21 jours',
    phone: '+212 5 24 XX XX XX',
    whatsapp: '+212661000023',
    features: ['Pompe incluse', 'Intérieur/Extérieur', 'Artisanat Marrakech', 'Pièce unique'],
  },
]

export function getProduitBySlug(slug: string): Produit | undefined {
  return PRODUITS.find((p) => p.slug === slug)
}

export function getProduitCardData(): ProduitCardData[] {
  return PRODUITS.map(({ slug, name, category, style, brand, city, price, oldPrice, images, isNew, isBestSeller, rating, reviewCount, deliveryTime, inStock, whatsapp }) => ({
    slug, name, category, style, brand, city, price, oldPrice, images, isNew, isBestSeller, rating, reviewCount, deliveryTime, inStock, whatsapp,
  }))
}

export function getSimilarProduits(slug: string, category: string, limit = 4): ProduitCardData[] {
  const all = getProduitCardData()
  const same = all.filter((p) => p.slug !== slug && p.category === category)
  if (same.length >= limit) return same.slice(0, limit)
  const others = all.filter((p) => p.slug !== slug && p.category !== category)
  return [...same, ...others].slice(0, limit)
}
